- name: Initialize and apply dotfiles via chezmoi
  ansible.builtin.command:
    cmd: >-
      {{ ansible_facts['user_dir'] }}/.pixi/bin/chezmoi init --apply
      --branch {{ dotfiles_branch }} {{ dotfiles_url }}
    creates: "{{ ansible_facts['user_dir'] }}/.local/share/chezmoi"
