// Package envlocal reads and writes ~/.env.local — the machine-local,
// never-versioned file sourced last by dot_bashrc.d/core/99-local.sh (see
// the main README's "Client / Server Differentiation" section). Converge
// owns the file's shape entirely: it's regenerated whole on every save
// from structured data, rather than patched in place, so the round trip
// only works for content that follows the generated shape below — which
// is also exactly the shape the main README already documents by hand.
package envlocal

import (
	"bufio"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strings"
)

// Export is one `export KEY=VALUE` line.
type Export struct {
	Key   string
	Value string
}

// PathVar is one guarded prepend-loop, e.g. PYTHONPATH built from a list
// of candidate directories that may or may not exist on this machine.
type PathVar struct {
	Name    string
	Entries []string // shell-expandable path expressions, in prepend order
}

// Env is the whole file.
type Env struct {
	Exports  []Export
	PathVars []PathVar
}

func path(homeDir string) string { return filepath.Join(homeDir, ".env.local") }

var (
	exportRe  = regexp.MustCompile(`^export ([A-Za-z_][A-Za-z0-9_]*)=(.*)$`)
	forRe     = regexp.MustCompile(`^for d in ((?:"[^"]*"\s*)+); do$`)
	loopVarRe = regexp.MustCompile(`^\s*\[ -d "\$d" \] && export ([A-Za-z_][A-Za-z0-9_]*)="\$d:\$[A-Za-z_][A-Za-z0-9_]*"$`)
	entryRe   = regexp.MustCompile(`"([^"]*)"`)
	doneRe    = regexp.MustCompile(`^done$`)
)

// Load parses ~/.env.local, or returns an empty Env if it doesn't exist.
// Lines it doesn't recognize (a hand edit that doesn't match the
// generated shape) are silently dropped on the next Save — Raw carries
// the untouched original so the UI can warn before that happens.
func Load(homeDir string) (env Env, raw string, err error) {
	data, err := os.ReadFile(path(homeDir))
	if os.IsNotExist(err) {
		return Env{}, "", nil
	}
	if err != nil {
		return Env{}, "", err
	}
	raw = string(data)

	scanner := bufio.NewScanner(strings.NewReader(raw))
	var lines []string
	for scanner.Scan() {
		lines = append(lines, scanner.Text())
	}

	for i := 0; i < len(lines); i++ {
		line := lines[i]
		if m := exportRe.FindStringSubmatch(line); m != nil {
			env.Exports = append(env.Exports, Export{Key: m[1], Value: m[2]})
			continue
		}
		if m := forRe.FindStringSubmatch(line); m != nil && i+2 < len(lines) {
			var entries []string
			for _, em := range entryRe.FindAllStringSubmatch(m[1], -1) {
				entries = append(entries, em[1])
			}
			if vm := loopVarRe.FindStringSubmatch(lines[i+1]); vm != nil && doneRe.MatchString(strings.TrimSpace(lines[i+2])) {
				env.PathVars = append(env.PathVars, PathVar{Name: vm[1], Entries: entries})
				i += 2
			}
		}
	}
	return env, raw, nil
}

// Matches reports whether raw is exactly what Save would (re)generate for
// env — used to warn before a save would discard unrecognized hand edits.
func (env Env) Matches(raw string) bool {
	return raw == "" || env.render() == raw
}

func (env Env) render() string {
	var b strings.Builder
	b.WriteString("# ~/.env.local — not versioned, managed directly on each machine.\n")
	b.WriteString("# Generated by Converge; see converge/README.md.\n\n")
	for _, e := range env.Exports {
		fmt.Fprintf(&b, "export %s=%s\n", e.Key, e.Value)
	}
	for _, pv := range env.PathVars {
		if len(env.Exports) > 0 || pv.Name != env.PathVars[0].Name {
			b.WriteString("\n")
		}
		fmt.Fprintf(&b, "# %s\n", pv.Name)
		b.WriteString("for d in ")
		for i, e := range pv.Entries {
			if i > 0 {
				b.WriteString(" ")
			}
			fmt.Fprintf(&b, "%q", e)
		}
		b.WriteString("; do\n")
		fmt.Fprintf(&b, "    [ -d \"$d\" ] && export %s=\"$d:$%s\"\n", pv.Name, pv.Name)
		b.WriteString("done\n")
	}
	return b.String()
}

// Save regenerates ~/.env.local from env, whole.
func (env Env) Save(homeDir string) error {
	return os.WriteFile(path(homeDir), []byte(env.render()), 0o644)
}
