include ./theme.conf 

font_family JetBrainsMono Nerd Font
bold_font   JetBrainsMono Nerd Font Bold
italic_font JetBrainsMono Nerd Font Italic
bold_italic_font auto

font_size 13.0

enable_ligatures always

hide_window_decorations yes

# Neovim like splits
enabled_layouts splits,stack

# Splits sur touches libres (- = horizontal, \ = vertical, façon tmux)
# (on évite ctrl+shift+v/s = coller / coller-sélection)
map ctrl+shift+minus     launch --location=hsplit --cwd=current
map ctrl+shift+backslash launch --location=vsplit --cwd=current

map ctrl+shift+h neighboring_window left
map ctrl+shift+j neighboring_window down
map ctrl+shift+k neighboring_window up
map ctrl+shift+l neighboring_window right

map alt+shift+h resize_window narrower
map alt+shift+j resize_window shorter
map alt+shift+k resize_window taller
map alt+shift+l resize_window wider
map alt+shift+0 reset_window_sizes

map ctrl+shift+q close_window

map ctrl+shift+t new_tab_with_cwd
map ctrl+shift+right next_tab
map ctrl+shift+left previous_tab
