- name: Install dev pixi global tools
  ansible.builtin.include_role:
    name: core
    tasks_from: pixi
  vars:
    pixi_tools: "{{ dev_pixi_tools }}"

- import_tasks: nvim.yml
- import_tasks: tiger_vnc.yml
- import_tasks: golang.yml
