# Read-only theme repos: no update once cloned, no become (user-space).
- name: Install kovidgoyal kitty themes
  ansible.builtin.git:
    repo: "https://github.com/kovidgoyal/kitty-themes.git"
    dest: "{{ ansible_facts['user_dir'] }}/.config/kitty/themes/kovidgoyal-kitty-themes"
  become: false

- name: Install dexpota kitty themes
  ansible.builtin.git:
    repo: "https://github.com/dexpota/kitty-themes.git"
    dest: "{{ ansible_facts['user_dir'] }}/.config/kitty/themes/dexpota-kitty-themes"
  become: false
