- name: Install kovidgoyal kitty themes
  ansible.builtin.git:
    repo: "https://github.com/kovidgoyal/kitty-themes.git"
    dest: {{ lookup('env', 'HOME') }}/.config/kitty/themes/kovidgoyal-kitty-themes

- name: Install dexpota kitty themes
  ansible.builtin.git:
    repo: "https://github.com/dexpota/kitty-themes.git"
    dest: {{ lookup('env', 'HOME') }}/.config/kitty/themes/dexpota-kitty-themes

