- hosts: localhost
  become: false
  roles:
    - core

    - role: desktop
      when: layers.desktop

    - role: gnome
      when: layers.gnome

    - role: gaming
      when: layers.gaming

    - role: dev
      when: layers.dev

    - role: drawing
      when: layers.drawing

